spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudstorage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  client:
    endpoint: http://localhost:9000
    user: minioadmin
    password: minioadmin
  bucket-name: user-files